# Generated by Django 5.1.4 on 2025-02-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
    ]
