# Generated by Django 5.1.4 on 2025-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20250219_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(default='not_paid', editable=False, max_length=20),
        ),
    ]
