# Generated by Django 5.1.4 on 2025-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_job_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=20),
        ),
    ]
