# Generated by Django 5.1.4 on 2025-02-26 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_job_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
