# Generated by Django 5.1.4 on 2025-02-26 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_job_job_date_alter_job_date_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vehicle_reg',
            field=models.CharField(help_text='Format: XX-00-XX-0000 (e.g., KA-05-AJ-6807)', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_vehicle_reg', message='Enter a valid vehicle registration number (e.g., KA-05-AJ-6807).', regex='^[A-Z]{2}-[0-7][0-9]-[A-Z]{2}-\\d{4}₹')]),
        ),
    ]
